import {useEffect,useRef,useState} from 'react';
import {ArrowUp,Bot,Sparkles,UserRound} from 'lucide-react';
import {useApp,api,money} from '../context/AppContext';
import {Button,Card,cn} from '../components/ui';
export function Chat(){
 const {scope,data}=useApp();const [messages,setMessages]=useState<any[]>([]),[input,setInput]=useState(''),[typing,setTyping]=useState(false),[llm,setLlm]=useState(true);const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{setMessages([])},[scope]);useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[messages,typing]);
 async function send(text=input){const question=text.trim();if(!question||typing)return;setInput('');setMessages(m=>[...m,{role:'user',text:question}]);setTyping(true);try{const result=await api('/assistant/chat',{message:question,scope,use_llm:llm});setMessages(m=>[...m,{role:'assistant',text:result.answer,source:result.mode==='llm'?'AI · подтверждённые расчёты':'Локальное объяснение · без LLM'}])}catch(e){setMessages(m=>[...m,{role:'assistant',text:e.message,source:'Ошибка запроса — можно повторить'}])}finally{setTyping(false)}}
 return <div className="mx-auto max-w-3xl"><p className="text-sm font-medium text-lilac">AI-помощник</p><h1 className="mb-6 mt-2 text-3xl font-bold">Чат</h1><Card className="overflow-hidden p-4 sm:p-6"><div className="max-h-[55dvh] min-h-64 space-y-4 overflow-y-auto" aria-live="polite">{!messages.length&&<div className="rounded-2xl bg-surface p-5"><Bot className="mb-3 text-lilac"/><p>Помогу разобраться, куда уходят деньги и хватит ли их до стипендии.</p><p className="mt-3 text-sm text-muted">Известный баланс: {money(data?.balance_minor)}. Все суммы берутся из расчётов приложения.</p></div>}{messages.map((m,i)=><div key={i} className={cn('flex gap-3',m.role==='user'&&'justify-end')}><span className={cn('flex h-8 w-8 shrink-0 items-center justify-center rounded-full',m.role==='user'?'order-2 bg-lime text-white':'bg-lilac/10 text-lilac')}>{m.role==='user'?<UserRound size={16}/>:<Bot size={16}/>}</span><div className="max-w-[85%]"><p className={cn('whitespace-pre-wrap rounded-2xl p-3 text-sm leading-relaxed',m.role==='user'?'rounded-tr-sm bg-lime text-white':'rounded-tl-sm bg-surface')}>{m.text}</p>{m.source&&<small className="text-muted">{m.source}</small>}</div></div>)}{typing&&<p className="text-sm text-muted">Помощник готовит ответ…</p>}<div ref={end}/></div><div className="my-4 flex flex-wrap gap-2">{['Хватит ли денег до стипендии?','Куда уходят деньги?','Что изменилось после покупки?'].map(q=><button disabled={typing} key={q} onClick={()=>send(q)} className="rounded-full border border-line px-3 py-2 text-xs text-muted hover:text-lime"><Sparkles className="mr-1 inline" size={12}/>{q}</button>)}</div><label className="mb-3 flex items-center gap-2 text-xs text-muted"><input type="checkbox" checked={llm} onChange={e=>setLlm(e.target.checked)}/>Использовать LLM, если настроена</label><form onSubmit={e=>{e.preventDefault();send()}} className="flex gap-2 rounded-2xl border border-line p-2"><input aria-label="Вопрос помощнику" maxLength={1000} value={input} onChange={e=>setInput(e.target.value)} placeholder="Введите запрос" className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none"/><Button disabled={typing||!input.trim()} size="icon" aria-label="Отправить"><ArrowUp size={18}/></Button></form></Card></div>
}
