import { useMemo, useState } from 'react'
import { ArrowRight, CarFront, ChevronRight, Cloud, Coffee, MoreHorizontal, Music2, Phone, Utensils } from 'lucide-react'
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts'
import { useRouter } from 'next/navigation'

import { money as formatMoney, useApp } from '../context/AppContext'
import { Badge, Button, Card, InfoTip, Progress } from '../components/ui'
import type { Category } from '../types'

const categoryIcons: Record<Category, typeof Coffee> = { Еда: Utensils, Транспорт: CarFront, Подписки: Music2, Учёба: MoreHorizontal, Другое: MoreHorizontal }
const paymentColorClasses: Record<string, string> = { lilac: 'bg-lilac/10 text-lilac', lime: 'bg-lime/10 text-lime', sun: 'bg-sun/10 text-sun' }
const money = (value: number) => formatMoney(value).replace(/\s*₽$/, '')
const compactMoney = (minor: number) => new Intl.NumberFormat('ru-RU', {notation: 'compact', maximumFractionDigits: 1}).format(minor / 100)

export function Dashboard() {
  const [activeCategory, setActiveCategory] = useState<string | null>(null)
  const navigate = useRouter().push
  const { transactions, data } = useApp()
  if(!data)return null
  const palette=['#237a51','#7168b4','#a96f13','#c84f45','#658a9e'];
  const spendingByCategory=data.categories.filter(x=>x.amount_minor>0).map((x,i)=>({name:x.name,value:x.amount_minor,color:palette[i%palette.length]}));
  const recurringPayments=data.recurring.map(x=>({title:x.name,date:new Date(x.due_date).toLocaleDateString('ru-RU'),amount:x.amount_minor,color:'lime',icon:'phone'}));
  const goal={title:data.settings.goal_title||'Моя цель',saved:data.settings.goal_saved_minor,target:data.settings.goal_minor};
  const total = spendingByCategory.reduce((sum, item) => sum + item.value, 0)
  const selectedTransactions = transactions.filter(t=>(t.user_category||t.bank_category)===activeCategory)

  return <div>
    <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-medium text-lime">Обзор</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Финансы</h1></div><Button variant="outline" size="sm" onClick={() => navigate('/transactions')}>Все операции <ArrowRight size={14} /></Button></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <Card className="border-lime/20 bg-soft p-5 sm:p-8"><div className="flex items-center gap-2 text-sm font-medium text-muted">Свободно до стипендии <InfoTip>Известный баланс минус обязательные платежи, резерв и операции в обработке.</InfoTip></div><div className="mt-3 flex flex-wrap items-end gap-x-3 gap-y-1"><span className="text-5xl font-bold tracking-tight text-ink sm:text-6xl" data-testid="available-budget">{money(data.available_minor)}</span><span className="mb-2 text-xl text-muted">₽</span><Badge color={data.deficit_minor?'coral':'lime'}>{data.available_minor==null?'нужен остаток':data.deficit_minor?'дефицит':'доступно'}</Badge></div><div className="mt-6 flex max-w-lg gap-3 rounded-xl bg-white p-3"><p className="text-sm leading-relaxed text-muted">Прогнозируемый остаток до поступления: <strong className="text-ink">{formatMoney(data.forecast_minor)}</strong>.</p></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-4"><div><p className="text-[11px] uppercase tracking-wide text-muted">Баланс сейчас</p><p className="mt-1 text-lg font-semibold" data-testid="known-balance">{formatMoney(data.balance_minor)}</p></div><div><p className="text-[11px] uppercase tracking-wide text-muted">До стипендии</p><p className="mt-1 text-lg font-semibold">{data.days_remaining} дн.</p></div><div><p className="text-[11px] uppercase tracking-wide text-muted">Лимит в день</p><div className="mt-1 flex items-center gap-1 text-lg font-semibold text-lime" data-testid="daily-budget">{formatMoney(data.daily_limit_minor)} <InfoTip>Доступные средства, разделённые на дни до следующего поступления.</InfoTip></div></div></div></Card>
      <Card className="p-4 sm:p-6"><div className="mb-1 flex items-center justify-between"><div><p className="text-sm font-semibold">Расходы по категориям</p><p className="mt-1 text-xs text-muted">30 дней · {money(total)} ₽</p></div><InfoTip>Категория определена по названию операции.</InfoTip></div><div className="mt-2 flex flex-col items-center gap-3 sm:flex-row"><div className="relative h-40 w-40 shrink-0 sm:h-[190px] sm:w-[190px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={spendingByCategory} dataKey="value" nameKey="name" innerRadius={51} outerRadius={72} paddingAngle={3} stroke="none" onClick={(entry) => setActiveCategory(entry.name)}>{spendingByCategory.map((entry) => <Cell key={entry.name} fill={entry.color} className="cursor-pointer outline-none" opacity={activeCategory && activeCategory !== entry.name ? .35 : 1} />)}</Pie><Tooltip contentStyle={{ background: '#fff', border: '1px solid #d5e0d9', borderRadius: 10, fontSize: 11 }} formatter={(value) => [`${money(Number(value))} ₽`, 'Расходы']} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="max-w-[92px] truncate whitespace-nowrap text-center text-sm font-bold">{compactMoney(total)}</span><span className="text-[10px] text-muted">рублей</span></div></div><div className="flex w-full min-w-0 flex-1 flex-col gap-2">{spendingByCategory.map((item) => <button key={item.name} onClick={() => setActiveCategory(activeCategory === item.name ? null : item.name)} className="flex items-center justify-between gap-3 rounded-lg px-2 py-1.5 text-left hover:bg-surface"><span className="flex min-w-0 items-center gap-2 text-xs text-muted"><span className="h-2 w-2 shrink-0 rounded-full" style={{ background: item.color }} /><span className="truncate">{item.name}</span></span><span className="shrink-0 text-xs font-semibold text-ink">{money(item.value)} ₽</span></button>)}</div></div>{activeCategory && <div className="mt-2 border-t border-line pt-3"><p className="mb-2 text-xs font-semibold">{activeCategory}: последние операции</p>{selectedTransactions.slice(0, 3).map((item) => <div key={item.id} className="flex justify-between gap-3 py-1 text-xs text-muted"><span className="truncate">{item.merchant_name||item.description}</span><span className="shrink-0 text-ink">{money(item.amount_minor)} ₽</span></div>)}</div>}</Card>
    </div>
    <section className="mt-7"><div className="mb-3 flex items-end justify-between"><div><p className="text-lg font-semibold">Регулярные платежи</p><p className="mt-1 text-xs text-muted">Предстоящие списания</p></div><button onClick={() => navigate('/settings')} className="text-xs font-semibold text-lime">Все <ChevronRight size={14} className="inline" /></button></div><div className="-mx-1 flex gap-3 overflow-x-auto px-1 pb-2">{recurringPayments.map((item) => <Card key={item.title} className="min-w-[190px] flex-1 p-4"><div className="flex items-start justify-between"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${paymentColorClasses[item.color]}`}>{item.icon === 'music' ? <Music2 size={17} /> : item.icon === 'phone' ? <Phone size={17} /> : <Cloud size={17} />}</div><span className="text-[10px] text-muted">{item.date}</span></div><p className="mt-5 text-xs text-muted">{item.title}</p><p className="mt-1 text-base font-semibold">{money(item.amount)} ₽</p></Card>)}</div></section>
    <div className="mt-7"><Card className="p-5 sm:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="text-lg font-semibold">Прогресс к цели</p><p className="mt-1 text-xs text-muted">{goal?.title ?? 'Нет активной цели'}</p></div><Button variant="ghost" size="icon" aria-label="Открыть цели" onClick={() => navigate('/goals')}><ArrowRight size={17} /></Button></div>{goal ? <div className="flex flex-col items-center gap-5 sm:flex-row"><div className="relative flex h-24 w-24 shrink-0 items-center justify-center rounded-full" style={{ background: `conic-gradient(#237a51 ${Math.round(goal.saved / goal.target * 100)}%, #e3ebe6 0)` }}><div className="flex h-[76px] w-[76px] flex-col items-center justify-center rounded-full bg-white"><span className="text-lg font-bold">{Math.round(goal.saved / goal.target * 100)}%</span><span className="text-[9px] text-muted">собрано</span></div></div><div className="text-center sm:text-left"><p className="text-xl font-bold">{money(goal.saved)} <span className="text-sm font-normal text-muted">из {money(goal.target)} ₽</span></p><p className="mt-2 text-xs leading-relaxed text-muted">Осталось накопить {formatMoney(Math.max(0,goal.target-goal.saved))}.</p></div></div> : <p className="text-sm text-muted">Создайте цель на странице «Цели».</p>}</Card></div>
  </div>
}
