import {useState} from 'react';
import {Target,Check,Pencil} from 'lucide-react';
import {useApp,money,minor} from '../context/AppContext';
import {Button,Card,Dialog,Input,Progress,Badge} from '../components/ui';
export function Goals(){
 const {data,saveSettings}=useApp();const [open,setOpen]=useState(false),[title,setTitle]=useState(''),[target,setTarget]=useState(''),[saved,setSaved]=useState(''),[deadline,setDeadline]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);if(!data)return null;
 const s=data.settings;const pct=Math.min(100,Math.floor(s.goal_saved_minor*100/s.goal_minor));
 function edit(){setTitle(s.goal_title||'Моя цель');setTarget(String(s.goal_minor/100));setSaved(String(s.goal_saved_minor/100));setDeadline(s.goal_deadline||'');setError('');setOpen(true)}
 async function save(){setBusy(true);setError('');try{if(!title.trim())throw new Error('Укажите название цели');await saveSettings({goal_title:title.trim(),goal_minor:minor(target),goal_saved_minor:minor(saved),goal_deadline:deadline||null});setOpen(false)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-sm font-medium text-sun">Накопления</p><h1 className="text-4xl font-bold">Цели</h1><p className="mt-2 text-sm text-muted">План накоплений и текущий прогресс.</p></div><Button onClick={edit}><Pencil size={16}/>Изменить цель</Button></div><Card className="border-lilac/20 bg-lilac/5 p-6 sm:p-9"><div className="flex flex-col items-center justify-between gap-8 md:flex-row"><div className="w-full min-w-0"><Badge color="lilac">Активная цель</Badge><h2 className="mt-4 break-words text-3xl font-bold">{s.goal_title||'Моя цель'}</h2><p className="mt-2 text-sm text-muted">{s.goal_deadline?'Срок: '+new Date(s.goal_deadline).toLocaleDateString('ru-RU'):'Срок пока не задан'}</p><p className="mt-8 text-3xl font-bold">{money(s.goal_saved_minor)} <span className="text-sm font-normal text-muted">из {money(s.goal_minor)}</span></p><Progress value={pct} color="lilac" className="mt-4 h-3"/><p className="mt-3 text-sm text-muted">Осталось накопить {money(Math.max(0,s.goal_minor-s.goal_saved_minor))}</p></div><div className="flex h-44 w-44 shrink-0 items-center justify-center rounded-full" style={{background:`conic-gradient(#7168b4 ${pct}%, #e3ebe6 0)`}}><div className="flex h-36 w-36 flex-col items-center justify-center rounded-full bg-panel"><Target className="mb-2 text-lilac"/><b className="text-3xl">{pct}%</b><span className="text-xs text-muted">собрано</span></div></div></div></Card><Card className="mt-5 p-5"><h2 className="font-semibold">Твой план</h2><p className="mt-2 text-sm text-muted">Обновляй накопленную сумму после пополнения. Цель сохраняется для выбранного профиля. Без истории пополнений срок достижения не прогнозируем.</p></Card><Dialog open={open} onClose={()=>setOpen(false)} title="Настроить цель"><form onSubmit={e=>{e.preventDefault();save()}} className="space-y-4"><label className="block text-sm">Название<Input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)}/></label><label className="block text-sm">Сумма цели, ₽<Input inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)}/></label><label className="block text-sm">Уже накоплено, ₽<Input inputMode="decimal" value={saved} onChange={e=>setSaved(e.target.value)}/></label><label className="block text-sm">Срок<Input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label>{error&&<p role="alert" className="text-sm text-coral">{error}</p>}<Button disabled={busy} className="w-full"><Check size={16}/>Сохранить</Button></form></Dialog></div>
}
