import Link from 'next/link';
import {FileText, ShieldCheck, Upload, WalletCards} from 'lucide-react';
import {useRouter} from 'next/navigation';
import {Button,Card} from '../components/ui';

export function Onboarding(){
 const navigate=useRouter().push;
 return <div className="min-h-screen bg-surface px-5 py-6 text-ink sm:px-8 sm:py-8"><div className="mx-auto flex min-h-[calc(100vh-64px)] max-w-5xl flex-col"><header className="flex items-center justify-between"><div className="flex items-center gap-2.5"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-lime text-white"><WalletCards size={19} strokeWidth={2.5}/></div><span className="text-lg font-bold tracking-tight">finly<span className="text-lime">.</span></span></div><span className="text-xs text-muted">PDF / CSV / демо</span></header><main className="mx-auto flex w-full max-w-2xl flex-1 flex-col justify-center py-14"><p className="mb-4 text-sm font-medium text-lime">Импорт данных</p><h1 className="max-w-xl text-4xl font-bold leading-[1.08] tracking-tight sm:text-6xl">Начни с выписки</h1><p className="mt-5 max-w-lg text-base leading-relaxed text-muted">Загрузи обезличенную PDF- или CSV-выписку. Перед сохранением можно проверить и исправить операции.</p><Card className="mt-10 p-5 sm:p-7"><div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-lime/40 bg-lime/5 px-5 py-12 text-center"><span className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-lime text-white"><Upload size={25}/></span><span className="text-sm font-semibold">PDF или CSV · до 8 МБ</span><span className="mt-2 text-xs text-muted">PDF обрабатывается через LLM только после проверки очищенного текста и твоего согласия.</span></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-surface px-3 py-2.5 text-xs text-muted"><ShieldCheck size={15} className="shrink-0 text-lime"/>Загрузка и подтверждение доступны на следующем шаге.</div><Button className="mt-5 w-full" onClick={()=>navigate('/imports')}><FileText size={16}/>Перейти к импорту</Button><button onClick={()=>navigate('/dashboard')} className="mt-4 w-full text-center text-xs font-medium text-lime hover:underline">Посмотреть учебные данные без загрузки</button></Card></main><footer className="text-center text-[11px] text-muted">Локальный прототип · реальные банковские счета не подключаются.<br/><Link href="/privacy" className="mt-2 inline-block text-lime hover:underline">Политика конфиденциальности</Link></footer></div></div>
}
