import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {FileUp,Search,Receipt} from 'lucide-react';
import {useApp,api,money} from '../context/AppContext';
import {Badge,Button,Card,EmptyState} from '../components/ui';
export function Transactions(){
 const {transactions,data,refresh,setError}=useApp();const navigate=useRouter().push;
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[busy,setBusy]=useState(false);
 const categories=Array.from(new Set<string>([...(data?.settings.categories||[]),...transactions.map(t=>t.user_category||t.bank_category||'Другое')]));
 const filtered=transactions.filter(t=>(!category||(t.user_category||t.bank_category)===category)&&(!query||(t.description+' '+(t.merchant_name||'')).toLowerCase().includes(query.toLowerCase()))&&(!from||t.occurred_at.slice(0,10)>=from)&&(!to||t.occurred_at.slice(0,10)<=to));
 async function change(id:string,value:string){setBusy(true);try{await api('/transactions/'+id,{user_category:value},'PATCH');await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function refund(id:string){setBusy(true);try{await api('/simulator/transactions/'+id+'/refund',{});await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-medium text-lilac">История операций</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Траты</h1><p className="mt-2 text-sm text-muted">{filtered.length} операций · расходы, поступления и переводы</p></div><Button onClick={()=>navigate('/imports')}><FileUp size={17}/>Загрузить выписку</Button></div>
 <Card className="mb-5 p-4"><div className="flex flex-wrap gap-3"><label className="relative min-w-48 flex-1"><Search className="absolute left-3 top-3 text-muted" size={16}/><input aria-label="Поиск операций" placeholder="Поиск по магазину" value={query} onChange={e=>setQuery(e.target.value)} className="h-11 w-full rounded-xl border border-line bg-panel pl-9 pr-3 text-sm"/></label><select aria-label="Категория" className="rounded-xl border border-line bg-panel p-2 text-sm" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Все категории</option>{categories.map(c=><option key={c}>{c}</option>)}</select><label className="text-xs text-muted">С даты<input aria-label="С даты" type="date" className="block rounded-lg border border-line bg-panel p-2" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs text-muted">По дату<input aria-label="По дату" type="date" className="block rounded-lg border border-line bg-panel p-2" value={to} onChange={e=>setTo(e.target.value)}/></label></div></Card>
 <Card className="overflow-hidden">{filtered.length?filtered.map(t=><div key={t.id} className="grid grid-cols-[1fr_auto] items-center gap-3 border-b border-line px-4 py-4 last:border-0 sm:grid-cols-[95px_minmax(0,1fr)_170px_130px]"><span className="text-xs text-muted">{new Date(t.occurred_at).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}</span><div className="min-w-0"><p className="break-words text-sm font-medium">{t.merchant_name||t.description}</p><p className="mt-1 text-[11px] text-muted">{({manual_import:'Выписка',bank_in_a_box:'Учебный банк',personal_simulator:'Симулятор'})[t.source_type]} · {({posted:'Проведена',pending:'В обработке',reversed:'Отменена',unknown:'Статус неизвестен'})[t.status]}{t.direction==='transfer'?' · свой перевод':''}</p></div><select aria-label={'Категория: '+(t.merchant_name||t.description)} className="min-w-0 rounded-lg border border-line bg-panel p-2 text-xs" disabled={busy} value={t.user_category||t.bank_category||'Другое'} onChange={e=>change(t.id,e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><div className="text-right"><span className={'whitespace-nowrap text-sm font-semibold '+(t.amount_minor>0?'text-lime':'')}>{t.amount_minor>0?'+':''}{money(t.amount_minor,t.currency)}</span>{t.source_type==='personal_simulator'&&t.status==='posted'&&t.direction==='expense'&&t.amount_minor<0&&<button disabled={busy} onClick={()=>refund(t.id)} className="mt-1 block w-full text-right text-xs text-lime">Возврат</button>}</div></div>):<EmptyState icon={<Receipt/>} title="Нет операций" description="Измените фильтры или импортируйте выписку." action={<Button onClick={()=>navigate('/imports')}>Импортировать</Button>}/>}</Card></div>
}
