'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {LayoutDashboard,List,MessageCircle,Target,WalletCards,Upload,Plug,FlaskConical,Bell,Settings,ChartNoAxesCombined,CalendarDays,Sparkles,Sun,Moon,Menu,X,RefreshCw} from 'lucide-react';
import {AppProvider,useApp} from './context/AppContext';
import {Button,cn} from './components/ui';
import {Dashboard} from './screens/Dashboard';
import {Transactions} from './screens/Transactions';
import {Goals} from './screens/Goals';
import {Chat} from './screens/Chat';
import {Onboarding} from './screens/Onboarding';
import FinanceApp from '../components/finance-app';
const primary=[['/dashboard','Обзор',LayoutDashboard],['/transactions','Траты',List],['/goals','Цели',Target],['/chat','AI-помощник',MessageCircle]] as const;
const secondary=[['/imports','Импорт выписки',Upload],['/analytics','Аналитика',ChartNoAxesCombined],['/budget','До стипендии',CalendarDays],['/connections','Подключения',Plug],['/lab','Демо-лаборатория',FlaskConical],['/notifications','Уведомления',Bell],['/settings','Настройки',Settings],['/pricing','Free / Pro',Sparkles]] as const;
function Shell(){
  const raw=usePathname(),path=raw==='/'?'/dashboard':raw;const navigate=useRouter().push;
 const {data,scope,setScope,error,setError,loading,connected,refresh}=useApp();const [menu,setMenu]=useState(false),[theme,setTheme]=useState('light');
 useEffect(()=>{const saved=localStorage.getItem('stipendia-theme')||'light';setTheme(saved);document.documentElement.dataset.theme=saved},[]);
 useEffect(()=>setMenu(false),[path]);
 function toggle(){const next=theme==='light'?'dark':'light';setTheme(next);document.documentElement.dataset.theme=next;localStorage.setItem('stipendia-theme',next)}
 function brand(){return <button onClick={()=>navigate('/dashboard')} className="flex items-center gap-2.5 text-left"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-lime text-white"><WalletCards size={19} strokeWidth={2.5}/></span><span className="text-xl font-bold tracking-tight">finly<span className="text-lime">.</span></span></button>}
 function nav(items:typeof primary|typeof secondary){return items.map(([url,label,Icon])=><button key={url} onClick={()=>navigate(url)} aria-current={path===url?'page':undefined} className={cn('flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium transition-colors',path===url?'bg-lime/10 text-lime':'text-muted hover:bg-surface hover:text-ink')}><Icon size={18}/>{label}{url==='/notifications'&&data?.unread_count>0&&<span className="ml-auto text-xs">{data.unread_count}</span>}</button>)}
 const extra=secondary.some(([p])=>p===path);
  if(path==='/onboarding')return <div className="finly"><Onboarding/></div>;
  return <div className="finly min-h-screen bg-surface text-ink">{menu&&<button aria-label="Закрыть меню" onClick={()=>setMenu(false)} className="fixed inset-0 z-30 bg-ink/25 lg:hidden"/>}<aside className={cn('fixed inset-y-0 left-0 z-40 flex w-[236px] flex-col overflow-y-auto border-r border-line bg-panel px-5 py-7 transition-transform lg:translate-x-0',menu?'translate-x-0':'-translate-x-full')}><div className="mb-9 flex items-center justify-between">{brand()}<button onClick={()=>setMenu(false)} aria-label="Скрыть меню" className="lg:hidden"><X size={18}/></button></div><nav className="space-y-1">{nav(primary)}</nav><p className="mb-2 mt-7 px-3 text-[10px] font-semibold uppercase tracking-widest text-muted">Управление финансами</p><nav className="space-y-1">{nav(secondary)}</nav><div className="mt-auto pt-7"><div className="rounded-xl bg-soft p-4"><p className="text-sm font-semibold text-lime">{data?.demo_pro?'Pro · демонстрация':'Free · твой бюджет'}</p><p className="mt-2 text-xs leading-relaxed text-muted">Только учебные счета и обезличенные выписки.</p></div></div></aside>
 <main className="min-h-screen pb-24 lg:ml-[236px] lg:pb-8"><div className="mx-auto max-w-[1320px] px-4 py-5 sm:px-8 sm:py-7 lg:px-12 lg:py-9"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3 lg:hidden"><button aria-label="Открыть меню" onClick={()=>setMenu(true)}><Menu size={22}/></button>{brand()}</div><div className="flex flex-wrap items-center gap-3 text-xs text-muted"><span className={'flex items-center gap-1.5 '+(connected?'text-lime':'')}><span className={'h-1.5 w-1.5 rounded-full '+(connected?'bg-lime':'bg-coral')}/>{connected?'Обновления онлайн':'Переподключение…'}</span><span className="rounded-full bg-lime/10 px-2 py-1 font-semibold text-lime">{data?.demo_pro?'PRO · ДЕМО':'FREE'}</span></div><div className="flex items-center gap-4"><button aria-label="Обновить данные" onClick={refresh}><RefreshCw size={17}/></button><button aria-label="Сменить тему" onClick={toggle}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><button aria-label="Открыть уведомления" onClick={()=>navigate('/notifications')} className="relative"><Bell size={18}/>{data?.unread_count>0&&<span className="absolute -right-1 -top-1 h-2 w-2 rounded-full bg-coral"/>}</button></div></header>
 <div className="mb-7 flex flex-wrap items-center justify-between gap-3 border-b border-line pb-4"><p className="max-w-md text-xs leading-relaxed text-muted">{scope==='statements'||scope==='personal'?'Аналитика по последней загруженной выписке':'Синтетический профиль · реальные деньги не используются'}<br/>{scope==='statements'||scope==='personal'?(data?.last_import_at?'Импорт: '+new Date(data.last_import_at).toLocaleString('ru-RU'):'Выписок пока нет'):(data?.last_bank_sync?'Банк обновлён: '+new Date(data.last_bank_sync).toLocaleString('ru-RU'):'Банк ещё не подключён')}</p><select aria-label="Источник аналитики" value={scope} onChange={e=>setScope(e.target.value)} className="max-w-full rounded-xl border border-line bg-panel px-3 py-2 text-xs"><option value="demo">Учебный банк + симулятор</option><option value="statements">Демо-выписки · Free</option><option value="personal">Мои выписки</option><option value="bank">Только учебный банк</option></select></div>
 {error&&<div role="alert" className="mb-5 flex items-center justify-between gap-3 rounded-xl border border-coral/25 bg-coral/5 p-4 text-sm text-coral"><span>{error}</span><button aria-label="Закрыть ошибку" onClick={()=>setError('')}><X size={18}/></button></div>}
 {loading&&!data?<div role="status" className="space-y-5"><p className="text-muted">Загружаем финансы…</p><div className="h-64 animate-pulse rounded-2xl bg-soft"/></div>:<>{path==='/dashboard'&&<Dashboard/>}{path==='/transactions'&&<Transactions/>}{path==='/goals'&&<Goals/>}{path==='/chat'&&<Chat/>}{extra&&<div className="legacy-finance"><FinanceApp embedded activeScope={scope}/></div>}{!extra&&!primary.some(([p])=>p===path)&&<div><h1 className="text-2xl font-bold">Страница не найдена</h1><Button onClick={()=>navigate('/dashboard')}>Перейти к обзору</Button></div>}</>}
 <footer className="mt-10 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-5 text-xs text-muted"><span>finly · хакатонный прототип</span><Link href="/privacy" className="hover:text-lime hover:underline">Политика конфиденциальности</Link></footer>
 </div></main><nav className="fixed inset-x-0 bottom-0 z-20 flex min-h-[70px] items-center justify-around border-t border-line bg-panel/95 px-1 pb-[env(safe-area-inset-bottom)] backdrop-blur lg:hidden">{primary.map(([url,label,Icon])=><button key={url} onClick={()=>navigate(url)} className={cn('flex min-w-0 flex-1 flex-col items-center gap-1 px-1 py-2 text-[10px] font-medium',path===url?'text-lime':'text-muted')}><Icon size={19}/>{label}</button>)}<button onClick={()=>setMenu(true)} className="flex flex-1 flex-col items-center gap-1 text-[10px] text-muted"><Menu size={19}/>Ещё</button></nav></div>
}
export default function FinlyApp(){return <AppProvider><Shell/></AppProvider>}
